.TH "ascript var call" 3

.SH NAME
.EX
ascript var call

.SH COPYRIGHT
.EX
By Kyle Sallee in 2018 copyrighted.

.SH ARGOT
.EX
.in -8
.TS
llll.
\fBargot	target	origin 	task\fR
var call	`new name`	var	The var is renamed.
.TE
.in
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a,	var
target origin	`easy`	way.too.long.older.var
var call
\fR
.in

.SH THE VAR ADDRESS DOES NOT CHANGE.
.EX
The type env
the tri  link
the type ray
the host var
the sub  var
the memberships are sustained.

.SH SUB VAR CAVEAT
.EX
A   host var when      renamed
the sub  var are  not  renamed.
New sub  var when      created
the host var new  name is used.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript          was created.
In 2018; by Kyle Sallee; argot   var call was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript var
man 5 ascript
man 7 ascript
\fR
