.TH "ascript uname" 3
.SH NAME
.EX
ascript uname

.SH COPYRIGHT
.EX
By Kyle Sallee in 2018 copyrighted.

.SH HOSTED VAR
.EX
.TS
lll.
\fBname	type	provide\fR
uname.domainname	byte	NIS or YP name
uname.machine	byte	Hardware architecture name.
uname.nodename	byte	DNS name
uname.release	byte	Kernel version
uname.sysname	byte	Kernel name
uname.version	byte	Compile information
.TE
.ta T 8n

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript       was created.
In 2018; by Kyle Sallee; argot   uname was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 2 uname
man 5 ascript
man 7 ascript
\fR
