.TH "ascript fun" 5

.SH NAME
.EX
ascript operator

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH C LANGUAGE FUNCTIONS
.EX
In     the C   language functions  do not exist.
Rather the asm language procedures was    copied.
For    CPU register     use inane  rules  were inflicted.
That   blatant copy     was called function.

.SH ASCRIPT LANGUAGE FUNCTIONS
.EX
In  ascript  functions exist.
The function aft       definition
the value    when      accessed
the function is        performed.

.SH WHAT ARE FUNCTIONS CALLED?
.EX
Ascript functions are called fun.

.SH WHAT FUN?
.EX
An arithmetic operation is performed.

.SH WHY FUN?
.EX
A fun       when  declared many opcodes execute.
A fun value when  accessed few  opcodes execute.
More  than  thrice
the   value when  accessed is   faster.

.SH FUN NAMES
.EX
By file ascript\ fun.3 the function argot names are provided.

.SH FUN COMBOS
.EX
As a fun operand a fun result can be used.
Rather than a single arithmetic operation
in parts an entire equation can be defined.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript           was created.
In 2019; by Kyle Sallee; ascript functions was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript fun
man 3 ascript int
man 5 ascript
man 5 ascript operator
man 5 ascript var
man 7 ascript
\fR
