.TH "ascript var" 3
.SH NAME
.EX
ascript var

.SH COPYRIGHT
.EX
By Kyle Sallee in 2016 copyrighted.

.SH HOSTED ARGOT
.EX
.in -8
.TS
lll.
\fBargot	make	task\fR
var call		The     var      rename.
var name	*	In target the origin var name acquire.
var len 	*.len	Text length adjustment sub var make.
var size	*.size	Text size   adjustment sub var make.
var terse	var.terse	The     var names       provide.
var verbose	var.verbose	Verbose var information provide.
.TE
.in
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a,	io
var,	var terse,		var verbose
out	var.terse	`\\n`	var.verbose
\fR
.in

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript     was created.
In 2017; by Kyle Sallee; argot   var was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript var call
man 3 ascript var len
man 3 ascript var name
man 3 ascript var size
man 5 ascript
man 7 ascript
\fR
