.TH "ascript per_linux32" 3
.SH NAME
.EX
ascript per_linux32

.SH COPYRIGHT
.EX
By Kyle Sallee in 2016 copyrighted.

.SH SYNOPSIS
.EX
per_linux32

.SH TERSE
.EX
The opcode      ret until   executed
to  PER_LINUX32 the process personality changes.
By  progeny         process
the progenitor      process personality is  inherited.

.SH SUCCESS
.EX
The next argot is skipped.

.SH FAILURE
.EX
The errno value is set.

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a
call
per_linux32
go	'per fail'
pin	"compile_software"
ret
\fR
.in

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript             was created.
In 2016; by Kyle Sallee; argot   per_linux32 was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 7 ascript
\fR
