.TH "ascript go" 3
.SH NAME
.EX
ascript go

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH SYNOPSIS
.EX
.TS
lll.
\fBargot	direct parameter	task\fR
go	'near'	At label interpret.
go	"far"	At label interpret.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.in -8
\fB
a,	io
go		'next'
out now		`This line never  outputs.\\n`
\&'next'
out now 	`This line always outputs.\\n`
\fR
.in

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript    was created.
In 2019; by Kyle Sallee; argot   go was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript a
man 5 ascript
man 7 ascript
\fR
