.TH "ascript dub flock" 3

.SH NAME
.EX
ascript dub flock

.SH COPYRIGHT
.EX
By Kyle Sallee in 2018 copyrighted.

.SH SYNOPSIS
.EX
.TS
lll.
\fBargot	type	task\fR
dub flock        	.dub	With wait the lock make.
dub flock now    	.dub	Sans wait the lock make.
dub flock free   	.dub	Sans wait the lock free.
dub flock free late	.dub	On   ret  the lock free.
.TE
.ta T 8n

.SH SKIP
.EX
The  argot dub flock
the  argot dub flock now
when successful      the next argot is skipped.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript           was created.
In 2019; by Kyle Sallee; argot   dub flock was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 2 flock
man 3 ascript dub
man 5 ascript
man 7 ascript
\fR
