.TH "ascript lax" 3
.SH NAME
.EX
ascript lax

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH SYNOPSIS
.EX
.TS
ll.
\fBargot	task\fR
lax	The following argot is unoptimized.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.in -8
\fB
lax
+
\fR
.in

.SH WHY?
.EX
Most argot  on next  invocation fewer opcodes execute.
For  an     operator argot
the  target operand  type       if    changed
the  wrong  opcode   sequence   executes.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript     was created.
In 2019; by Kyle Sallee; argot   lax was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript a
man 5 ascript
man 7 ascript
\fR
