.TH "ascript next" 3
.SH NAME
.EX
ascript next

.SH COPYRIGHT
.EX
By Kyle Sallee in 2016 copyrighted.

.SH TERSE
.EX
The next argot is interpreted.

.SH EXAMPLE
.EX
.in -8
\fB
a, io
name	A,	byte,	scope
target origin	A	`/tmp/a`,	io load,	next
\fR
.in

.SH EXAMPLE 2
.EX
.in -8
\fB
a
name	A,	byte,	scope,	origin	`/tmp/a`,	@
\fR
.in

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript      was created.
In 2016; by Kyle Sallee; argot   next was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript a
man 3 ascript err
man 3 ascript trek
man 5 ascript
man 7 ascript
\fR
