.TH "ascript duct" 5

.SH NAME
.EX
ascript duct

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH WHAT IS A DUCT
.EX
By a duct a resource,
such as   air
such as   data
such as   water, is conveyed.

.SH DUCT TYPES
.EX
Type pipe
type mem
type tmp files
are  provided.

.SH DUCT USE
.EX
To   dub 1 the data is output
from dub 0 the data is  input.

.SH DUCT WHY
.EX
Among processes for data mastication
from dub 0 the data is acquired, chewed and into
into dub 1 spat.

.SH ASCRIPT DUCTS
.EX
Ascript ducts   are  efficient!
To      program task delegation since seldom
the     duct    are  seldom     useful.

.SH DUCT PIPE
.EX
Among two processes concurrently running the data drips.

.SH DUCT MEM
.EX
In  memory the  data           is stored.
All data   when stored the dub is rewound and
as  dub 0       provided.

.SH DUCT TMP FILE
.EX
The duct mem        and
the duct tmp        are  similar.
The data generation when excessive
to  the  filesystem is   stored.

.SH INFINITE OUTPUT
.EX
Infinite   output  when generated,
such as by program yes,
a    pipe  must    be   used.

.SH SPEED
.EX
Pipes  are slow.
Files  are fast.
Memory is  faster.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 duct
man 5 ascript
man 7 ascript
\fR
