.TH "ascript ret" 3

.SH NAME
.EX
ascript ret

.SH COPYRIGHT
.EX
By Kyle Sallee in 2016 copyrighted.

.SH ARGOT call
.EX
The argot  call when invoked
the opcode call is   executed
the interpretation   continues.

.SH ARGOT ret
.EX
The argot  ret  when invoked
the opcode ret  is   executed
the interpretation   continues.

.SH RIP
.EX
RIP and instruction pointer register are tantamount.

.SH CALL & RET
.EX
The opcode call when executed to   the stack the  RIP content is sent.
The opcode ret  when executed from the stack the  RIP content is set.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript     was created.
In 2016; by Kyle Sallee; argot   ret was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.
.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript call
man 5 ascript
man 7 ascript
\fR
