.TH "ascript far equal" 3

.SH NAME
.EX
ascript far equal

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH SYNOPSIS
.EX
.TS
llll.
\fBargot	target	origin	task\fR
far equal	"new name"	"old name"	The far label rename.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
io,	trek
target origin	"cat"		"kitten",	far equal
target origin	"kitten"	"dog",		far equal
pin		"kitten"
out		`moo\\n`,	ret

"dog",		out	`arf\\n`,	pin	"cat",	ret
"kitten",	out	`meow\\n`,			ret
\fR
.in

.SH EXAMPLE OUTPUT
.EX
arf
meow
moo

.SH EXAMPLE 1
.EX
.in -8
\fB
pin		"INIT"
\&...,	ret

"INIT"
\&...
target origin	"INITDONE"	"INIT",	far equal,	ret
"already init",	ret
\fR
.in

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript           was created.
In 2019; by Kyle Sallee; argot   far equal was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript trek
man 5 ascript
man 7 ascript
\fR
