.TH "ascript node sub fill" 3

.SH NAME
.EX
ascript node sub fill

.SH COPYRIGHT
.EX
By Kyle Sallee in 2018 copyrighted.

.SH SYNOPSIS
.EX
.TS
lllll.
\fBargot   	host	make	compat	task\fR
node sub fill	byte	*.fill	int 8	For node fill
        	dub	*.fill	int 8	acquire  and modify
        				a   sub  var make.
.TE
.ta T 8n

.SH SUCCESS
.EX
The value when  revised in the var metadata as success
the errno value is stored.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript               was created.
In 2018; by Kyle Sallee; argot   node sub size was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript node sub
man 3 posix_fallocate
man 5 ascript
man 7 ascript
\fR
