.TH "ascript go late" 3
.SH NAME
.EX
ascript go late

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH SYNOPSIS
.EX
.TS
lll.
\fBargot	direct data	task\fR
go late	'near'	The opcode ret when executed to the label go.
go late	"far"	The opcode ret when executed to the label go.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a,	io,	trek
go late		'later'
\&...,		out	`Not done yet.\\n`,	ret
\&'later',	out	`Now done yes.\\n`,	ret
\fR
.in

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript         was created.
In 2019; by Kyle Sallee; argot   go late was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript trek
man 5 ascript
man 7 ascript
\fR
