.TH "ascript dub on use wait" 3
.SH NAME
.EX
ascript dub on use wait

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH SYNOPSIS
.EX
.TS
lll.
\fBargot	want	task\fR
dub on use wait	*.dub	O_NONBLOCK unset and skip.
.TE
.TA
.ta T 8n

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript                 was created.
In 2019; by Kyle Sallee; argot   dub on use rush was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 2 fcntl
man 2 open
man 3 ascript dub
man 5 ascript
man 7 ascript
\fR
