.TH "ascript list unique" 3
.SH NAME
.EX
ascript list unique

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH ARGOT
.EX
.TS
lllll.
\fBargot   	host	make 	compat	task\fR
list unique	*.list	*.unique	byte	Unknown topics provide.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a,	io
name		B,	byte,	scope,	origin	`/tmp/basket`,@
name		A,	byte,	scope,	origin	`/tmp/fruits`,@,list
target		A.list,	list unique
target origin	A.list.unique	B,=
out		A.list.unique
\fR
.in

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript             was created.
In 2019; by Kyle Sallee; argot   list unique was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript list
man 5 ascript
man 7 ascript
\fR
