.TH "ascript segfault" 3
.SH NAME
.EX
ascript segfault

.SH COPYRIGHT
.EX
By Kyle Sallee in 2018 copyrighted.

.SH TERSE
.EX
The argot segfault    when invoked
on        segfault
verbose   information is   provided.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript          was created.
In 2018; by Kyle Sallee; argot   segfault was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript segfault
man 5 ascript
man 7 ascript
\fR
