.TH "ascript dub name" 3
.SH dub name
.EX
ascript dub name

.SH COPYRIGHT
.EX
By Kyle Sallee in 2018 copyrighted.

.SH SYNOPSIS
.EX
.TS
llll.
\fBargot	host	make  	task\fR
dub name	.dub	*.name	sub var make
.TE
.TA
.ta T 8n

.TS
lll.
\fBsub var	content\fR
*.name	/proc/self/fd/...
.TE
.ta T 8n

.SH CAVEAT
.EX
The   Linux purported name
might not   be useful.
By    a     different process if opened
            different content
might be    referenced.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript          was created.
In 2018; by Kyle Sallee; argot   dub name was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript dub
man 5 ascript
man 7 ascript
\fR
