.TH "ascript trek" 3
.SH NAME
.EX
ascript trek

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH HOSTED ARGOT
.EX
.TS
ll.
\fBargot	task\fR
context free	The saved     context  release.
context get	CPU registers save and skip.
context set	CPU registers load and the  skipped argot interpret.
far equal	The far       label    name change.
.TE

.TS
llll.
\fBargot	direct	direct	task\fR
go 2	"far"	'near'	The aft far label near label reach.
go end	"far"		On   script end   reach.

go late	"far"		The  opcode ret   when executed
go late		'near'	the  label        reach.

pin 2	"far"	'near'	The aft far label near label visit.

weir	"far"		The                    label visit.
weir		'near'

weir next			The  opcode ret   aft  execution
			the  next   argot interpret.

weir next ret			The  opcode ret        execute.
			The  next   argot interpret.

weir skip			The  opcode ret   aft  execution
        			the  next   argot skip.

weir skip ret			The  opcode ret        execute.
        			The  next   argot skip.
.TE
.ta T 8n

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript      was created.
In 2020; by Kyle Sallee; argot   trek was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript context get
man 3 ascript err
man 3 ascript go 2
man 3 ascript go end
man 3 ascript go late
man 3 ascript pin 2
man 3 ascript tag
man 3 ascript weir
man 5 ascript
man 5 ascript trek
man 7 ascript
\fR
