.TH "ascript argot info" 3
.SH NAME
.EX
ascript argot info

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH HOSTED ARGOT
.EX
.TS
llll.
\fBargot	host	make	type\fR
argot info	byte	*.author    	byte
        		*.author.email	byte
        		*.contact   	byte
        		*.contact.email	byte
        		*.homepage  	byte
        		*.create    	byte
        		*.official  	byte
        		*.update    	byte
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a,	io
name		A,	byte,	scope,	argot info
set		`int`
out		`The argot int author is `	A.author	`\\n`
\fR
.in

.SH DATE
.EX
For the date YEARMODA denary format is used.

.SH HOST VAR CONTENT
.EX
For the host var an argot filename is required.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript          was created.
In 2019; by Kyle Sallee; argot argot info was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript argot alias
man 3 ascript argot info
man 3 ascript argot load
man 5 ascript
man 7 ascript
\fR
