.TH "ascript argot alias" 3
.SH NAME
.EX
ascript argot alias

.SH COPYRIGHT
.EX
By Kyle Sallee in 2017 copyrighted.

.SH HOSTED ARGOT
.EX
.TS
llll.
\fBargot	require	require	task\fR
argot alias	`new_name`	`old_name`	For the argot a new name make.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a
target object	`to`	`targetobject`,	argot alias
to		`aa`	`argotalias`,	argot alias
to		`t`	`target`,	aa
to		`o`	`object`,	aa
\fR
.in

.SH FAIL
.EX
A segfault becomes.

.SH ARGOT NAME SIZE LIMIT
.EX
16 bytes exist.

.SH ARGOT NAME PROHIBITED BYTE VALUES
.EX
Tab         9 x,
line feed   a x,
space      20 x

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript             was created.
In 2016; by Kyle Sallee; argot   argot alias was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript argot alias
man 3 ascript argot info
man 3 ascript argot load
man 5 ascript
man 7 ascript
\fR
