.TH "ascript var len" 3
.SH NAME
.EX
ascript var len

.SH COPYRIGHT
.EX
By Kyle Sallee in 2017 copyrighted.

.SH ARGOT
.EX
.TS
lllll.
\fBargot	host	make	compat	use\fR
var len	byte compat	*.len	int 4	The text length is provided.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a,	io,	var
name	ball,	byte,	scope,	var len,	set	`Blue`
out	`The length is `	ball.len	`.\\n`
\fR
.in

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript         was created.
In 2017; by Kyle Sallee; argot   var len was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript var
man 5 ascript
man 7 ascript
\fR
