.TH "ascript node sub attr" 3

.SH NAME
.EX
ascript node sub attr

.SH COPYRIGHT
.EX
By Kyle Sallee in 2018 copyrighted.

.SH ARGOT
.EX
.TS
lllll.
\fBargot	host	make	compat	task\fR
node sub attr	byte	*.attr	int 8	For node ext attribute
        	dub	*.attr	int 8	acquire  and modify
        				a   sub  var make.
.TE

.SH HOSTED VAR
.EX
EXT2_SECRM_FL
EXT2_UNRM_FL
EXT2_COMPR_FL
EXT2_SYNC_FL
EXT2_IMMUTABLE_FL
EXT2_APPEND_FL
EXT2_NODUMP_FL
EXT2_NOATIME_FL
EXT2_DIRTY_FL
EXT2_COMPRBLK_FL
EXT2_NOCOMPR_FL
EXT4_ENCRYPT_FL
EXT2_BTREE_FL
EXT2_INDEX_FL
EXT2_IMAGIC_FL
EXT3_JOURNAL_DATA_FL
EXT2_NOTAIL_FL
EXT2_DIRSYNC_FL
EXT2_TOPDIR_FL
EXT4_HUGE_FILE_FL
EXT4_EXTENTS_FL
EXT4_EA_INODE_FL
FS_NOCOW_FL
EXT4_SNAPFILE_FL
EXT4_SNAPFILE_DELETED_FL
EXT4_SNAPFILE_SHRUNK_FL
EXT4_INLINE_DATA_FL
EXT4_PROJINHERIT_FL
EXT2_RESERVED_FL
EXT2_FL_USER_VISIBLE
EXT2_FL_USER_MODIFIABLE

.SH SUCCESS
.EX
The value when  revised in the var metadata as success
the errno value is stored.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript               was created.
In 2018; by Kyle Sallee; argot   node sub attr was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript node sub
man 5 ascript
man 7 ascript
less  /usr/include/ext2fs/ext2_fs.h
\fR
