.TH "ascript clone" 5
.SH NAME
.EX
ascript clone

.SH COPYRIGHT
.EX
By Kyle Sallee in 2018 copyrighted.

.SH NOT STACK
.EX
On the stack script salient data is not stored.

.SH WHY NOT STACK?
.EX
More   opcodes  must     execute.
CPU    register pressure increases.
Slower performance       results.

.SH WHICH CLONE WHEN?
.EX
A   script  interpreting ascript process clone  must not become.
A   single  argot        ascript process clone  can      become.
For sorting shared       memory  process clones are      created.

.SH COW
.EX
For  script   interpretation
a    progeny  process when   created
copy on write memory  can be inherited.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 5 ascript
man 7 ascript
\fR
