.TH "ascript memory dub" 5
.SH NAME
.EX
ascript memory dub

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH dub
.EX
A dub is a nickname.

.SH C LANGUAGE DUB
.EX
In the C language a dub when acquired is called a file descriptor,
however not merely files are described, almost anything
can be described.

.SH ASCRIPT DUB
.EX
In the      ascript  language
a  dub when acquired
a  numeric  nickname for a use approved resource
is          acquired.

.SH ASCRIPT DUB OR C DESCRIPTOR
.EX
An       ascript dub being var encapsulated is superior.
However, the     dub value and
a        descriptor  value are the same.

.SH PROCESS START
.EX
At       process    start
from the progenitor process
for  dub 0
for  dub 1
for  dub 2
the      references and flags are inherited.

.SH PROBABLY REFERENCE?
.EX
By dub 0
by dub 1
by dub 2
a  terminal or a file is probably referenced.

.SH TRADITIONAL DUB USE
.EX
From dub 0 data   is read.
To   dub 1 output is written.
To   dub 2 errput is written.

.SH DUB 100 x
.EX
The dub 0         through 255
by  the script    author  are    typically used.
By  dub 100 x the argot   dir is referenced.

.SH ABOVE DUB 100 x
.EX
By  ascript argot
at  values  above dub 100 x dub dups are typically made.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript dub
man 5 ascript
man 7 ascript
\fR
