.TH "ascript tutorial e" 5

.SH NAME
.EX
ascript tutorial e

.SH COPYRIGHT
.EX
By Kyle Sallee in 2018 copyrighted.

.SH DATA EXTRACTION
.EX
A    type   byte var content
the pare method
the trim method
the view method glossed?

.SH LINE EXTRACTION
.EX
From a type byte var content
the  line extraction method glossed?

.SH REGULAR EXPRESSION
.EX
By noobs hackers as a first resort regular expression is used.
By elite hackers as a last  resort regular expression is used.
Faster methods      differ.
More   learning  is required.

.SH WHY NOT STRAIGHT UP INDEXING?
.EX
With sub var .view.from
with sub var .view.size  straight up indexing is possible.
Byte sequences if manually compared
the  best      performance might not result.

.SH THE COST
.EX
That same argot in that same position when next invoked
at least 20 opcodes less execute.
The next argot to reach at least 3 opcodes must execute.
Less than eloquent techniques if wielded more overhead is executed.

.SH OPTIMIZATION
.EX
Far groups and      near groups  why  create?
An  argot  group    when created that argot sequence is factored out.
The argot  sequence when next    invoked    fewer opcodes execute.
The argot  sequence when looped             fewer opcodes execute.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript              was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 5 ascript
man 5 ascript f
man 7 ascript
\fR
