.TH "ascript ray now" 3

.SH NAME
.EX
ascript ray now

.SH COPYRIGHT
.EX
By Kyle Sallee in 2017 copyrighted.

.SH ARGOT
.TS
lllll.
\fBargot	host	make	compat	use\fR
ray now	ray	*.now	int	Ray index value.
.TE
.ta T 8n

.SH VAR *.now
.EX
The ray indexed address
can be  acquire and set.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript         was created.
In 2017; by Kyle Sallee; argot   ray now was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript ray
man 5 ascript
man 7 ascript
\fR
