.TH "ascript re" 3
.SH NAME
.EX
ascript re

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH HOST METHOD
.EX
The argot a  aft     invocation
the argot re     is  available.
the argot re aft     invocation
the argot re *   are available.

.SH HOSTED ARGOT
.EX
.TS
ll.
\fBargot	runs\fR
re 2  	2
re 3  	3
re 4  	4
re 5  	5
re 6  	6
re 7  	7
re 8  	8
re 9  	9
re a  	10
re b  	11
re c  	12
re d  	13
re e  	14
re f  	15
re 10	16
.TE
.ta T 8n

.SH 105 LINES OF Hi
.EX
.ta T 8n
.in -8
\fB
a,	io,	re
re 5		out	`Hi\\n`,	ret
re a,	re a,	out	`Hi\\n`,	ret,	ret
\fR
.in

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript    was created.
In 2019; by Kyle Sallee; argot   re was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript loop
man 3 ascript tag
man 3 ascript trek
man 5 ascript
man 7 ascript
\fR
