.TH "ascript tutorial d" 5

.SH NAME
.EX
ascript tutorial d

.SH COPYRIGHT
.EX
By Kyle Sallee in 2017 copyrighted.

.SH INDEXING
.EX
A   type byte var content can  be indexed.
The ambit         values  must be known.

.SH MULTIBYTE CHARACTER SUPPORT
.EX
Multibyte characters, UFF-8 encoded, is supported.

.SH FETCH
.EX
From  the above     information
using the ascript.5 manual page  as  a  start
the   salient argot manual pages can be located.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript              was created.
In 2017; by Kyle Sallee; ascript tutorial d.5 was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 5 ascript
man 5 ascript tutorial e
man 5 ascript var
man 7 ascript
\fR
