.TH "ascript mdk" 3
.SH NAME
.EX
ascript mdk

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH SYNOPSIS
.EX
.TS
llll.
\fBargot	host	make	use\fR
mdk	byte	*.mdk	Message digest generate.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a,	dub,	io
name		A,	byte,	scope,	io map,	dub file,	mdk

target origin	A.dub	`/tmp/cat\\0`
O_RDONLY,	@
go		'fail'
target origin	A.map	A.dub,=
out		A.mdk
\fR
.in

.SH SECURITY + PERFORMANCE
.EX
From all file content concatenate.
A    mdk generate and check.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript     was created.
In 2019; by Kyle Sallee; argot   mdk was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript mdk
man 3 ascript top
man 5 ascript
man 7 ascript
\fR
