.TH "ascript loop" 5
.SH NAME
.EX
ascript loop

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH LOOPS
.EX
The iteration amount decreases and until 0 the loop reiterates.

.SH ARGOT re *
.EX
The iteration  amount    when fixed    the argot re * suffice.

.SH ARGOT loop
.EX
The iterations remaining when required the argot loop suffices.

.SH WHY?
.EX
For  faster  than C loop performance
the  argot   loop
the  argot   re *   were created.

.SH PERFORMANCE
.EX
From slow to fast the following argot are ordered : go; loop; re.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript        was created.
In 2019; by Kyle Sallee; ascript loop.5 was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript loop
man 3 ascript re
man 3 ascript tag
man 3 ascript trek
man 5 ascript
man 5 ascript trek
man 7 ascript
\fR
