.TH "ascript lens" 3
.SH NAME
.EX
ascript lens

.SH COPYRIGHT
.EX
By Kyle Sallee in 2018 copyrighted.

.SH HOSTED ARGOT
.EX
.TS
llll.
\fBargot	from	task\fR
lens data	target origin	The  character sets acquire.

lens render	target origin	From origin    the  data
				is   acquired
				is   transliterated
				to   target appended.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a,	io
name		A,	byte,	scope,	set	`ascript is fast.`
name		B,	byte,	scope
lens
target origin	`abcdefghijklmnopqrstuvwxyz`	\\
		`ABCDEFGHIJKLMNOPQRSTUVWXYZ`,	lens data
target origin	B	A,			lens render
out		B
\fR
.in
.ta T 8n

.SH FLAT LENS DEFAULT
.EX
A   new UTF-8 value when not provided
the old UTF-8 value is       copied.

.SH ARGOT lens
.EX
The lens   afore bend
the argot  lens  when invoked
the old    lens  is   stored.
The opcode ret   when executed
the old    lens  is   restored.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript      was created.
In 2018; by Kyle Sallee; argot   lens was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript byte
man 5 ascript
man 7 ascript
\fR
