.TH "ascript pin 2" 3
.SH NAME
.EX
ascript pin 2

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.ta T 8n
.SH SYNOPSIS
.EX
.TS
llll.
\fBargot	direct	direct	task\fR
pin 2	"far"	'near'	At label visit.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a,	io,	trek
pin 2		"logger"	'selfy',	ret
"logger",	out		`This line never  outputs.\\n`,	ret
\&'selfy',	out		`This line always outputs.\\n`,	ret
\fR
.in

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript       was created.
In 2019; by Kyle Sallee; argot   pin 2 was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript pin
man 3 ascript trek
man 5 ascript
man 7 ascript
\fR
