.TH "ascript clock" 3
.SH NAME
.EX
ascript clock

.SH COPYRIGHT
.EX
By Kyle Sallee in 2018 copyrighted.

.SH HOSTED VAR
.EX
.TS
llll.
\fBvar	compat	duration provide\fR
boot.nano	int 4	since boot
boot.sec	int 8
mono.nano	int 4	since when?
mono.sec	int 8
process.nano	int 4	process use
process.sec	int 8
real.nano	int 4	since epoch
real.sec	int 8
thread.nano	int 4	thread  use
thread.sec	int 8
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
clock,	io
out	`real	`		real.sec	`.`	real.nano	`\\n`
out	`mono	`		mono.sec	`.`	mono.nano	`\\n`
out	`boot	`		boot.sec	`.`	boot.nano	`\\n`
out	`process	`	process.sec	`.`	process.nano	`\\n`
out	`thread	`		thread.sec	`.`	thread.nano	`\\n`
\fR
.in

.SH EPOCH
.EX
1970-01-01 00:00:00 +0000 (UTC).

.SH PADDING
.EX
For nanoseconds 9 digits output.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript       was created.
In 2017; by Kyle Sallee; argot   clock was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 1 date
man 2 clock_getres
man 3 ascript tm
man 5 ascript
man 7 ascript
man 8 hwclock
\fR
