.TH "ascript versus" 5

.SH NAME
.EX
ascript versus

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH FREEDOM
.EX
In   the freedom ascript    exists.
To   the paydom  export  is forbidden!
Use  liberty if  blocked if non free if can be sold
then ascript can not     be used.

.SH PAYDOM
.EX
Busybox toybox or whatever utility suite can be used.
It will not be faster.
It will not be free.
It will     be sold by bundling with something sold.

.SH A MEANINGFUL VOTE CAST
.EX
The freedom when expanded liberty      is  preserved.
The  paydom when expanded wage slavery is  inflicted.
Enslavement and  freedom               are available.
Which       one                        is  preferred?

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
lynx https://en.wikipedia.org/wiki/Toybox
man 1 ascript
man 5 ascript
man 7 ascript
\fR
