.TH "ascript ray cat" 3

.SH NAME
.EX
ascript ray cat

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH ARGOT
.EX
.TS
llll.
\fBargot	target	origin	task\fR
ray cat	ray	ray	From origin  ray
			to   target  ray
			the  content is appended.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
\&...
target origin	R0	R1
ray cat
\fR
.in

.SH CAVEAT
.EX
In   target a ray address
in   origin a ray address when contained
the  argot add            if   invoked
a    multi dimensional    ray  becomes.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript         was created.
In 2019; by Kyle Sallee; argot   ray cat was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript ray
man 5 ascript
man 7 ascript
\fR
