mandir		=	$(prefix)/share/man
.PHONY		:	all clean install
all		:
clean		:
install		:
	install -vm  755 -d $(DESTDIR)$(mandir)/man1
	install -vm  644 -t $(DESTDIR)$(mandir)/man1 *.1
	install -vm  755 -d $(DESTDIR)$(mandir)/man3
	install -vm  644 -t $(DESTDIR)$(mandir)/man3 *.3
	install -vm  755 -d $(DESTDIR)$(mandir)/man5
	install -vm  644 -t $(DESTDIR)$(mandir)/man5 *.5
	install -vm  755 -d $(DESTDIR)$(mandir)/man7
	install -vm  644 -t $(DESTDIR)$(mandir)/man7 *.7
