.TH "ascript readline" 3

.SH NAME
.EX
ascript readline

.SH COPYRIGHT
.EX
By Kyle Sallee in 2019 copyrighted.

.SH SYNOPSIS
.EX
.TS
llll.
\fBargot	direct-	parameters	task\fR
readline	input	prompt	The function readline is invoked.
.TE
.ta T 8n

.SH EXAMPLE
.EX
.ta T 8n
.in -8
\fB
a,	io
name		A,	byte,	scope
readline	A	`Awaiting input: \\0`
out now		A	` was received.\\n`
\fR
.in

.SH PROMPT STRING
.EX
With byte value 0 the prompt must be terminated.

.SH INPUT VAR
.EX
To  the     target   address  var      content
the library readline provided input is appended.

.SH PERFORMANCE
.EX
By  library readline
the ascript performance level is not attained.

.SH AUTHOR
.EX
In 2016; by Kyle Sallee; ascript          was created.
In 2019; by Kyle Sallee; argot   readline was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript readline
man 3 readline
man 8 readline
man 5 ascript
man 7 ascript
\fR
