.TH "initreal" 3
.SH NAME
.EX
initreal

.SH COPYRIGHT
.EX
By Kyle Sallee in 2017 copyrighted.

.SH TERSE
.EX
A    realFS sustaining process is created.
SIGCHLD  is received and ignored.
The process sleeps.

.SH AUTHOR
.EX
In 2017; by Kyle Sallee; initreal was created.

.SH LICENSE
.EX
By \fBman 7 ascript\fR the license is provided.

.SH SEE ALSO
.EX
\fB
man 1 ascript
man 3 ascript init
man 5 ascript
man 7 ascript
man 7 namespaces
man 8 initroot
\fR
