mandir		=	$(prefix)/share/man
.PHONY		:	all clean install posix
all		:
posix		:
clean		:
install		:
	install -vm  755 -d $(DESTDIR)$(mandir)/man3
	install -vm  644 -t $(DESTDIR)$(mandir)/man3 *.3
	install -vm  755 -d $(DESTDIR)$(mandir)/man8
	install -vm  644 -t $(DESTDIR)$(mandir)/man8 *.8
